version: "3.8"

services:
  usuario:
    build: .
    container_name: usuario-ms
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@pejajc0xxex9q5hh_high?TNS_ADMIN=/app/oracle-wallet/Wallet_PEJAJC0XXEX9Q5HH
      - SPRING_DATASOURCE_USERNAME=ADMIN
      - SPRING_DATASOURCE_PASSWORD=Barbara.2246
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    volumes:
      - ./oracle-wallet:/app/oracle-wallet:ro
    restart: unless-stopped
